

trigger:
- master

pool:
  name: 'agent1'

steps:
- script: cd /home/azureuser/myagent/_work/1/s;mvn package
  displayName: 'Build'
- script: scp /home/azureuser/myagent/_work/1/s/webapp/target/webapp.war azureuser@20.63.88.6:/var/lib/tomcat10/webapps/mytestapp.war
  displayName: DeployToQA
- script: git clone https://github.com/IntelliqDevops/FunctionalTesting.git
  displayName: DownloadSeleniumCode
- script: java -jar /home/azureuser/myagent/_work/1/s/FunctionalTesting/testing.jar
  displayName: RunSelenium
- script: scp /home/azureuser/myagent/_work/1/s/webapp/target/webapp.war azureuser@20.200.121.160:/var/lib/tomcat10/webapps/myprodapp.war
  displayName: DeployToProd
